title: Statistics of Common Crawl Monthly Archives
description: Number of pages, distribution of top-level domains, crawl overlaps, etc. - basic metrics about Common Crawl Monthly Crawl Archives

show_navigation: True
navlist:
 - title: Statistics Home
   url: 
 - title: CommonCrawl Home
   url: https://commoncrawl.org/
 - title: Size of crawls
   url: /plots/crawlsize
 - title: Top-level domains
   url: /plots/tlds
 - title: Crawler metrics
   url: /plots/crawlermetrics
 - title: Crawl overlaps
   url: /plots/crawloverlap
 - title: Media types
   url: /plots/mimetypes
 - title: Character sets
   url: /plots/charsets
 - title: Languages
   url: /plots/languages
 - title: Getting Started
   url: https://commoncrawl.org/the-data/get-started/
   
theme: jekyll-theme-minimal
